// <auto-generated />
namespace CapstoneProject_Ecommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class user_oggetto_messaggio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_oggetto_messaggio));
        
        string IMigrationMetadata.Id
        {
            get { return "202302241624425_user_oggetto_messaggio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
